### ISSUE TITLE
Support reverse geocoding

### ISSUE THREAD

**Issue by karussell** [graphhopper/geocoder-converter#11]
Nominatim and OCD support reverse geocoding and we should parse this as well

**Comment by boldtrn** [comment]
Thanks @karussell. We should support reverse geocoding if the provider supports it.

**Comment by boldtrn** [comment]
I just started with the reverse geocoding. Something I just found out is that if you query a reverse geocoding request to Nominatim you get one result (at least in my current test url). GraphHopper returns multiple results.

**Comment by boldtrn** [comment]
@karussell would you mind to review my changes in #12 please :)?

**Comment by boldtrn** [comment]
Should be fixed with #12 and #16
