### ISSUE TITLE
explicit street entry could be missing from OCD

### ISSUE THREAD

**Issue by karussell** [graphhopper/geocoder-converter#13]
name contains the street but the street is not (always) explicitly included.

**Comment by boldtrn** [comment]
Thanks for reporting this issue. Could you add an example, that we can use for testing/debugging this issue?

**Comment by karussell** [comment]
E.g. "KURSAAL WESTHELLING 5 8400 BELGIUM" results in

```
{"copyrights":["OpenCageData","OpenStreetMap","GraphHopper"],"hits":[{"point":{"lat":51.2310419,"lng":2.9121083},"name":"Kursaal Westhelling, 8400 Ostende, Belgien","country":"Belgien","city":"Ostende","state":"Flandern","osm_id":38256343,"osm_type":"W"},{"point":{"lat":51.2083,"lng":2.9167},"name":"8400 Flanders, Belgium","country":"Belgium","state":"Flanders","osm_id":-1,"osm_type":"N"}]}
```

**Comment by karussell** [comment]
It is not the street is it the pedestrian area I think, e.g. "KURSAAL WESTHELLING 5 8400 BELGIUM" results in a name "Kursaal Westhelling, ..." but no explicit street "Kursaal Westhelling" is existing. In OCD this is named 'pedestrian'. See [this nominatim link](http://nominatim.openstreetmap.org/search.php?q=Kursaal+Westhelling&polygon=1&format=json)

**Comment by boldtrn** [comment]
I just searched online for Kursaal Westhelling and found some sort of festival arena that has the following address as their postal address:

Kursaal-Westhelling 12, 8400 Oostende, Belgium

So to me it seems like that Kursaal-Westhelling is a street, isn't it?

BTW: This is the highway in OSM - http://www.openstreetmap.org/way/38256343

**Comment by karussell** [comment]
It is a street, yes, but OCD does not list it as street instead it uses 'pedestrian' (see my edited comments above)

**Comment by boldtrn** [comment]
I am currently debugging this issue. When I request "KURSAAL WESTHELLING 5 8400 BELGIUM" from OCD, I get two results. The first one is the pedestrian.

That contains the OSM part:

```
OSM: {
edit_url: "https://www.openstreetmap.org/edit?way=38256343#map=17/51.23104/2.91211",
type: "pedestrian",
url: "https://www.openstreetmap.org/?mlat=51.23104&mlon=2.91211#map=17/51.23104/2.91211"
}
```

And the components:

```
components: {
_type: "road",
city_district: "Oostende",
country: "Belgien",
country_code: "be",
county: "Ostende",
neighbourhood: "Vlaams Plein",
pedestrian: "Kursaal Westhelling",
postcode: "8400",
state: "Flandern",
town: "Ostende"
}
```

The display name from OCD is: `formatted: "Kursaal Westhelling, 8400 Ostende, Belgien"` and we are correctly wrapping that as name. Also the OSM Type seems to be correct as W?

What should be handled different in this case? should we use the components `_type`? I think we are currently not using the type at all, are we?

**Comment by karussell** [comment]
Thanks. Maybe we should fill the graphhopper `street` entry with 'Kursaal Westhelling'? I.e. this way users can directly access the street name even if it is pedestrian

**Comment by boldtrn** [comment]
I added a fix in #15, would you mind to review the changes?

**Comment by boldtrn** [comment]
@karussell How should we handle buildings? Buildings are along a road,  so we could add a street to these entries as well? 

A sample is the reverse geocoding lookup for:  48.6915° N, 9.4179° E

```
components: {
_type: "building",
city: "Wernau (Neckar)",
country: "Deutschland",
country_code: "de",
county: "Landkreis Esslingen",
house_number: "55",
postcode: "73249",
road: "Kirchheimer Straße",
state: "Baden-Württemberg",
state_district: "Regierungsbezirk Stuttgart"
}
```

We could add the house_number as well.

**Comment by karussell** [comment]
Yes, looks useful. And currently this is not included due to what reason?

**Comment by boldtrn** [comment]
> And currently this is not included due to what reason?

You mean the building or the house_number?

**Comment by karussell** [comment]
I meant: is the building entry included or skipped from the result list?

**Comment by boldtrn** [comment]
Building is included, but I meant, that we could add the `street` value for buildings, right now I only check for `_type=road` but we could check for `_type=road||building`.

Edit: Possible values of _type include (but are not limited to): building, road, village, neighbourhood, city, county, postcode, state_district, state, region, island, country, continent, ficticious, unknown

**Comment by karussell** [comment]
Maybe we include the street always, i.e. when it is available? (Same for the other properties)

Or would this make problems sometimes?

**Comment by boldtrn** [comment]
I don't this will create any issues. I will change this.

**Comment by boldtrn** [comment]
Ok, I added the HouseNumber and removed the isStreet check in https://github.com/boldtrn/graphhopper-geocoder-converter/commit/f33a8fa7da5bee8d5f7415fc48cae9edb4cc548f
