### ISSUE TITLE
[Nominatim] Adding Polygon to result

### ISSUE THREAD

**Issue by boldtrn** [graphhopper/geocoder-converter#19]
Nominatim allows to return the Polygon of the area a result covers by adding:

```
polygon_geojson=1
Output geometry of results in geojson format.
```

This might be a very interesting feature of Nominatim, that we should allow our users to use.  I have not found a similar feature for OpenCage in their documentation.

What do you think @karussell?

**Comment by karussell** [comment]
Not sure, they could be extremely big especially for relations etc

**Comment by boldtrn** [comment]
> Not sure, they could be extremely big especially for relations etc

I would only add the polygon if a user explicitly requests it. We should document that it might be big. Or would this be an issue considering traffic?

**Comment by karussell** [comment]
We can integrate it. But it is unlikely to be integrated in the Directions API because it would not scale with Nominatim and also OpenCage does probably not allow this at the moment (have to ask)

**Comment by boldtrn** [comment]
> extremely big especially for relations

You are right. For example the polygon of France is  about 15mb, that would be definitely too big.

> But it is unlikely to be integrated in the Directions API

Ok, mhm in this case it would make no sense for me to build it. Let's close this for now.
