### ISSUE TITLE
How to handle exceptions from our providers?

### ISSUE THREAD

**Issue by boldtrn** [graphhopper/geocoder-converter#28]
For example in #26 we requested an URL from Nominatim.
`http://nominatim.openstreetmap.org/reverse/?lat=NaN&lon=NaN&limit=5&format=json&email=&addressdetails=1&accept-language=en`

Nominatim returned an exception for this request. We try to convert that request to a regular response, which leads to an Exception. 

I think we should check the response code of the provider an either return a 400 ourselves or maybe even forward the exception of the provider? (Not sure if we want to do this due to security?)

**Comment by karussell** [comment]
We should use the code the provider uses, yes. As it is a 400er here this makes sense

> Not sure if we want to do this due to security?

Yes, probably not good sometimes
