### ISSUE TITLE
Should we rename to GeocodeConverter?

### ISSUE THREAD

**Issue by karussell** [graphhopper/geocoder-converter#3]
My intentions are to support multiple OpenStreetMap-based providers, not only nominatim in the long run. Would it make sense to rename it then?

**Comment by boldtrn** [comment]
Yes. Any proposals?

GraphHopperGeocoderConverter?

**Comment by karussell** [comment]
yes something like this or instead camel casing using dashes like `graphhopper-geocoder-converter` as this will be cloned into a file system and there I don't like upper cases due to windows etc :)

**Comment by boldtrn** [comment]
Ok, I renamed the repository.

Github recommends to run
`git remote set-url origin new_url`
