### ISSUE TITLE
Transfer

### ISSUE THREAD

**Issue by karussell** [graphhopper/geocoder-converter#32]
@boldtrn do you know what needs to be done to transfer this repo to graphhopper/geocoder-converter?

**Comment by boldtrn** [comment]
Yes, it appears to be a single click in the settings. Should I try it?

**Comment by karussell** [comment]
Yes :+1:

**Comment by boldtrn** [comment]
Seems to be done. Please check the access settings (read/write).

**Comment by karussell** [comment]
Thanks! Is done and have renamed it! Please check if you have still all rights :)
