### ISSUE TITLE
ArrayIndexOutOfBoundsException for jdk9

### ISSUE THREAD

**Issue by karussell** [graphhopper/geocoder-converter#35]
Probably we just need a dropwizard update

```
java.lang.ArrayIndexOutOfBoundsException: 1
	at org.hibernate.validator.internal.util.Version.getJavaRelease(Version.java:36)
```

**Comment by karussell** [comment]
Should be fixed in 1.3.0 https://github.com/dropwizard/dropwizard/pull/2197 but there is no final release on maven central yet. It seems that 1.2.4 fixes the issues but there are [others now](https://travis-ci.org/graphhopper/geocoder-converter/jobs/341409265)

**Comment by boldtrn** [comment]
Could you clarify how this error is reproducible? I just tried with `javac 10.0.2` from `java-1.11.0-openjdk`. The tests and a regular server start with a geocoding request is working. 

Or maybe this was fixed here: https://github.com/graphhopper/geocoder-converter/commit/58846e956d626eb00f04ebe44bf77f14ac8750e4

**Comment by boldtrn** [comment]
Or is this only happening with jdk9?

**Comment by boldtrn** [comment]
We could update Dropwizard to 1.3.X anyway?

**Comment by karussell** [comment]
I think I used jdk11. Is dropwizard 1.3 already released (?)

**Comment by boldtrn** [comment]
[It looks like it would be](https://mvnrepository.com/artifact/io.dropwizard/dropwizard-core).

**Comment by karussell** [comment]
Ah, ok. Then sure, feel free to upgrade :)

I probably mixed this up with 2.0.0 (https://github.com/graphhopper/graphhopper/issues/1558)

**Comment by boldtrn** [comment]
Ok, I created #56. I am not sure if we should close this issues afterwards?

**Comment by karussell** [comment]
We close it and I will reopen if I still see the problem
