### ISSUE TITLE
Switch to Nominatim HTTTPS

### ISSUE THREAD

**Issue by boldtrn** [graphhopper/geocoder-converter#37]
As announced [here](https://lists.openstreetmap.org/pipermail/geocoding/2018-January/001918.html) Nominatim will be soon only available via https.

Thanks @grischard who mentioned this [here](https://github.com/gisgraphy/gisgraphy/issues/22).

**Comment by grischard** [comment]
Great! Since [Jersey doesn't follow redirects by default](http://javadox.com/com.sun.jersey/jersey-client/1.8/com/sun/jersey/api/client/config/ClientConfig.html#PROPERTY_FOLLOW_REDIRECTS), this would turn into a nasty bug once the redirect is switched on.
