### ISSUE TITLE
county is missing from response

### ISSUE THREAD

**Issue by karussell** [graphhopper/geocoder-converter#50]
E.g. for point=48.4882,2.6996 "county": "Seine-et-Marne" should be returned like it is the case for the original response from OpenCageData

**Comment by freyfogle** [comment]
Hi, Ed from OpenCage here. 

Sorry for any confusion. Definitely it should be county, and as far as I can tell it is now always county. I am not able to recreate a case where it is state_district. 

We have added this as a specific test case on our side as well, if there is a change we will be aware and investigate

thanks for making us aware.
