### ISSUE TITLE
resource for photon

### ISSUE THREAD

**Issue by karussell** [graphhopper/geocoder-converter#61]
Currently we patched photon to get our custom response format, but I would like to avoid this and update to the most recent photon version. For that the simplest solution is to add it to the list of supported providers.

**Comment by boldtrn** [comment]
Ah I see, so Photon would be the default then? Or would you keep the current Geocoding server as it is and as default, and add Photon additionally?

**Comment by karussell** [comment]
We would need to set photon as default, yes (if no provider parameter is specified).  (I hope you meant this :) )

Currently we query photon directly, but this is only possible with a patched version. And I would like to use the most recent photon version without patching it. And so the easiest would be if we would add photon additionally here, so we would always query the geocoder converter regardless of the geocoder.

**Comment by boldtrn** [comment]
I see, thanks for the explanation, yes that should be easily possible :).

**Comment by boldtrn** [comment]
Photon and Pelias seem to both use more or less Geojson as the Response format. Maybe we could combine some of the classes used for Pelias and Photon?

**Comment by karussell** [comment]
I would keep them separated also because of the different progress and features. If on the way of implementing this identical things are needed then surely we can reuse stuff :) ?

**Comment by boldtrn** [comment]
Ok yes I think this makes sense :). The actual properties are quite different so the shared code is not that much.
